name: ServerTransfer
main: skh6075\ServerTransfer\ServerTransfer
author: AvasKr
api: 3.10.0
version: 1.0.0
website: https://github.com/GodVas

permissions:
  servertransfer.permission:
    default: op